# Generated by Django 4.1.3 on 2022-11-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('hours_of_operation_monday_open', models.TimeField()),
                ('hours_of_operation_monday_close', models.TimeField()),
                ('hours_of_operation_tuesday_open', models.TimeField()),
                ('hours_of_operation_tuesday_close', models.TimeField()),
                ('hours_of_operation_wenesday_open', models.TimeField()),
                ('hours_of_operation_wenesday_close', models.TimeField()),
                ('hours_of_operation_thursday_open', models.TimeField()),
                ('hours_of_operation_thursday_close', models.TimeField()),
                ('hours_of_operation_friday_open', models.TimeField()),
                ('hours_of_operation_friday_close', models.TimeField()),
                ('hours_of_operation_saturday_open', models.TimeField()),
                ('hours_of_operation_saturday_close', models.TimeField()),
                ('hours_of_operation_sunday_open', models.TimeField()),
                ('hours_of_operation_sunday_close', models.TimeField()),
            ],
        ),
    ]
