from django.db import models
from django import forms

class Restaurant(models.Model):
    restaurant_name = models.CharField(max_length=80)
    hours_of_operation_monday_open_hour =  models.IntegerField(null=True)
    hours_of_operation_monday_open_minutes = models.IntegerField(null=True)
    hours_of_operation_monday_open_am_pm =  models.CharField(max_length=100)
    hours_of_operation_monday_open_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_monday_close_hour =  models.IntegerField(null=True)
    hours_of_operation_monday_close_minutes = models.IntegerField(null=True)
    hours_of_operation_monday_close_am_pm =  models.CharField(max_length=100)
    hours_of_operation_monday_close_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_tuesday_open_hour =  models.IntegerField(null=True)
    hours_of_operation_tuesday_open_minutes = models.IntegerField(null=True)
    hours_of_operation_tuesday_open_am_pm =  models.CharField(max_length=100)
    hours_of_operation_tuesday_open_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_tuesday_close_hour =  models.IntegerField(null=True)
    hours_of_operation_tuesday_close_minutes = models.IntegerField(null=True)
    hours_of_operation_tuesday_close_am_pm =  models.CharField(max_length=100)
    hours_of_operation_tuesday_close_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_wenesday_open_hour =  models.IntegerField(null=True)
    hours_of_operation_wenesday_open_minutes = models.IntegerField(null=True)
    hours_of_operation_wenesday_open_am_pm =  models.CharField(max_length=100)
    hours_of_operation_wenesday_open_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_wenesday_close_hour =  models.IntegerField(null=True)
    hours_of_operation_wenesday_close_minutes = models.IntegerField(null=True)
    hours_of_operation_wenesday_close_am_pm =  models.CharField(max_length=100)
    hours_of_operation_wenesday_close_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_thursday_open_hour =  models.IntegerField(null=True)
    hours_of_operation_thursday_open_minutes = models.IntegerField(null=True)
    hours_of_operation_thursday_open_am_pm =  models.CharField(max_length=100)
    hours_of_operation_thursday_open_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_thursday_close_hour =  models.IntegerField(null=True)
    hours_of_operation_thursday_close_minutes = models.IntegerField(null=True)
    hours_of_operation_thursday_close_am_pm =  models.CharField(max_length=100)
    hours_of_operation_thursday_close_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_friday_open_hour =  models.IntegerField(null=True)
    hours_of_operation_friday_open_minutes = models.IntegerField(null=True)
    hours_of_operation_friday_open_am_pm =  models.CharField(max_length=100)
    hours_of_operation_friday_open_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_friday_close_hour =  models.IntegerField(null=True)
    hours_of_operation_friday_close_minutes = models.IntegerField(null=True)
    hours_of_operation_friday_close_am_pm =  models.CharField(max_length=100)
    hours_of_operation_friday_close_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_saturday_open_hour =  models.IntegerField(null=True)
    hours_of_operation_saturday_open_minutes = models.IntegerField(null=True)
    hours_of_operation_saturday_open_am_pm =  models.CharField(max_length=100)
    hours_of_operation_saturday_open_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_saturday_close_hour =  models.IntegerField(null=True)
    hours_of_operation_saturday_close_minutes = models.IntegerField(null=True)
    hours_of_operation_saturday_close_am_pm =  models.CharField(max_length=100)
    hours_of_operation_saturday_close_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_sunday_open_hour =  models.IntegerField(null=True)
    hours_of_operation_sunday_open_minutes = models.IntegerField(null=True)
    hours_of_operation_sunday_open_am_pm =  models.CharField(max_length=100)
    hours_of_operation_sunday_open_time =  models.TimeField(null=True, blank=True)
    hours_of_operation_sunday_close_hour =  models.IntegerField(null=True)
    hours_of_operation_sunday_close_minutes = models.IntegerField(null=True)
    hours_of_operation_sunday_close_am_pm =  models.CharField(max_length=100)
    hours_of_operation_sunday_close_time =  models.TimeField(null=True, blank=True)
